apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse_ds
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
      username: default
      secure: false
    secureJsonData:
      password: changeme
